// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

/**
 * Validates Supabase environment variables at runtime.
 * Throws a descriptive error if configuration is missing.
 * 
 * This ensures the application fails gracefully with a clear error message
 * rather than silently failing or crashing with cryptic errors.
 */
function validateSupabaseConfig(): { url: string; key: string } {
  const url = import.meta.env.VITE_SUPABASE_URL;
  const key = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

  if (!url || typeof url !== 'string' || url.trim() === '') {
    throw new Error(
      'Missing VITE_SUPABASE_URL environment variable. ' +
      'Please ensure your .env file contains VITE_SUPABASE_URL=your_supabase_url'
    );
  }

  if (!key || typeof key !== 'string' || key.trim() === '') {
    throw new Error(
      'Missing VITE_SUPABASE_PUBLISHABLE_KEY environment variable. ' +
      'Please ensure your .env file contains VITE_SUPABASE_PUBLISHABLE_KEY=your_supabase_key'
    );
  }

  return { url, key };
}

const { url: SUPABASE_URL, key: SUPABASE_PUBLISHABLE_KEY } = validateSupabaseConfig();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

/**
 * Helper function to safely execute Supabase queries with error handling.
 * Returns a standardized response format with error handling.
 */
export async function safeSupabaseQuery<T>(
  queryFn: () => Promise<{ data: T | null; error: unknown }>
): Promise<{ data: T | null; error: Error | null; isLoading: boolean }> {
  try {
    const result = await queryFn();
    
    if (result.error) {
      const error = result.error instanceof Error 
        ? result.error 
        : new Error(String(result.error));
      return { data: null, error, isLoading: false };
    }

    return { data: result.data, error: null, isLoading: false };
  } catch (error) {
    const err = error instanceof Error ? error : new Error(String(error));
    return { data: null, error: err, isLoading: false };
  }
}